# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false
right_format = "$shell $time"

[directory]
style = 'bold 35'
#fish_style_pwd_dir_length = 1000
truncation_length = 8
truncation_symbol = 'â€¦/'
format = '[$path]($style)[$read_only]($read_only_style) '

[c]
format = 'via [$name $version]($style)'

[python]
symbol = 'ğŸ '
python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']

[container]
format = '[$symbol \[$name\]]($style) '
diabled = false

[hostname]
ssh_only = false
format = 'ğŸ”ï¸  [$hostname](bold 214) '
disabled = false

[memory_usage]
threshold = 0
format = 'via $symbol [${ram}( \| ${swap})]($style) '

[shell]
bash_indicator = '[bash](37)'
zsh_indicator = '[zsh](37)'
disabled = false

[cmd_duration]
min_time = 500
format = 'took [$duration](bold bgblack)'

[time]
disabled = false
format = 'at [$time]($style) '
time_format = '%r'

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[[battery.display]]
threshold = 10
style = 'bold red'

# replace the 'â¯' symbol in the prompt with 'âœ'
[character] # the name of the module we are configuring is 'character'
success_symbol = '[\$](bold 37)' # the 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = '[\$](bold 37) '
vimcmd_symbol = '[v](green) '

